services:
  # --- Infrastructure ---
  mongodb:
    image: mongo:latest
    container_name: factorio-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - factorio-network

  mongo-express:
    image: mongo-express:latest
    container_name: factorio-db-ui
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin 
    networks:
      - factorio-network

  # --- Microservices ---

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: factorio-auth
    depends_on:
      - mongodb
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    networks:
      - factorio-network

  persistence-bridge:
    build: ./persistence-bridge
    container_name: persistence-bridge
    depends_on:
      - mongodb
      - validator-service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blueprints_db
      - VALIDATOR_URL=http://validator-service:3000/validate
    networks:
      - factorio-network

  validator-service:
    build: ./validator-service
    container_name: validator-service
    networks:
      - factorio-network
  logic-service:
    build: ./blueprint-logic
    container_name: logic-service
    depends_on:
      - persistence-bridge
    # ports:
    #   - "5000:3000" # Maps [Host Port]:[Container Port]
    networks:
      - factorio-network
    # Note: We won't expose ports here. 
    # Eventually, Kong API Gateway will handle the entry point.

  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - factorio-network

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - factorio-network

  kong:
    image: kong:latest
    container_name: kong-gateway
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - factorio-network

volumes:
  kong_data:
  mongo-data:

networks:
  factorio-network:
    driver: bridge