services:
  # --- Infrastructure ---
  mongodb:
    image: mongo:latest
    container_name: factorio-db
    ports:
      - "27017:27017"
    volumes:
      - ./my-db-folder:/data/db
    networks:
      - factorio-network

  mongo-express:
    image: mongo-express:latest
    container_name: factorio-db-ui
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin 
    networks:
      - factorio-network

  # --- Microservices ---

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: factorio-auth
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017
    networks:
      - factorio-network

  persistence-bridge:
    build: ./persistence-bridge
    container_name: persistence-bridge
    depends_on:
      - mongodb
      - validator-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/blueprints_db
      - VALIDATOR_URL=http://validator-service:3000/validate
    networks:
      - factorio-network
  validator-service:
    build: ./validator-service
    container_name: validator-service
    networks:
      - factorio-network
  logic-service:
    build: ./logic-service
    container_name: logic-service
    depends_on:
      - persistence-bridge
    networks:
      - factorio-network
    # Note: We won't expose ports here. 
    # Eventually, Kong API Gateway will handle the entry point.

networks:
  factorio-network:
    driver: bridge
